name: s3 sync action

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::594135622755:role/github-trust-role
          aws-region: us-east-2

      - name: sync bucket
        run: aws s3 sync ./files/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete
