name: S3 Sync and Deploy Java App to AWS Elastic Beanstalk

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}  # ARN del rol que se asume
          aws-region: ${{ secrets.AWS_REGION }}  # Región especificada en tus secretos

      # Build the Java application
      - name: Set up Java version
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Cambia según tu versión de Java
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean install  # Asegúrate de tener un pom.xml

      # Cargar el JAR a S3
      - name: Upload JAR to S3
        run: |
          aws s3 cp target/*.jar s3://${{ secrets.AWS_BUCKET_NAME }}/java-app.jar \
            --region ${{ secrets.AWS_REGION }}

      # Desplegar a Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name my-java-app \
            --version-label v1 \
            --source-bundle S3Bucket=${{ secrets.AWS_BUCKET_NAME }},S3Key=java-app.jar

          aws elasticbeanstalk update-environment \
            --environment-name my-java-env \
            --version-label v1
